"""Train posture Random Forest and export a browser scorer.

Input CSV columns: label, performer_id, session_id, pose_landmarks_json,
hand_landmarks_json. Landmark JSON is a list of [x, y, z] world coordinates.
"""
import argparse
import json
from pathlib import Path

import m2cgen as m2c
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import LeaveOneGroupOut, cross_val_score

from features import posture_features


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("csv", type=Path)
    parser.add_argument("--out", type=Path, default=Path("../lib/models/posture.generated.ts"))
    args = parser.parse_args()
    data = pd.read_csv(args.csv)
    features = [posture_features(json.loads(row.pose_landmarks_json), json.loads(row.hand_landmarks_json)) for row in data.itertuples()]
    model = RandomForestClassifier(n_estimators=30, max_depth=4, random_state=42, class_weight="balanced")
    groups = data["performer_id"].astype(str) + ":" + data["session_id"].astype(str)
    scores = cross_val_score(model, features, data["label"], cv=LeaveOneGroupOut().split(features, data["label"], groups))
    print(f"leave-one-session-out accuracy: {scores.mean():.3f} +/- {scores.std():.3f}")
    model.fit(features, data["label"])
    labels = json.dumps(list(model.classes_))
    code = m2c.export_to_javascript(model, function_name="scorePosture")
    wrapper = f'''// Generated by train_posture.py. Do not edit.
import type {{ ClassifierModel }} from "./types";

const labels = {labels};
{code}
export const postureModel: ClassifierModel = {{
    trained: true,
    predict(features) {{
        const values = scorePosture(features);
        const probabilities = Object.fromEntries(labels.map((label, index) => [label, values[index] ?? 0]));
        const label = labels[values.indexOf(Math.max(...values))];
        return {{ label, probabilities }};
    }},
}};
'''
    args.out.write_text(wrapper, encoding="utf-8")


if __name__ == "__main__":
    main()