"""Train stroke-level articulation Random Forest and export JavaScript."""
import argparse
import json
from pathlib import Path

import m2cgen as m2c
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import LeaveOneGroupOut, cross_val_score

FEATURE_COLUMNS = ["duration_ms", "mean_speed", "speed_variance", "note_onset_count"]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("csv", type=Path)
    parser.add_argument("--out", type=Path, default=Path("../lib/models/articulation.generated.ts"))
    args = parser.parse_args()
    data = pd.read_csv(args.csv)
    model = RandomForestClassifier(n_estimators=30, max_depth=4, random_state=42, class_weight="balanced")
    groups = data["performer_id"].astype(str) + ":" + data["session_id"].astype(str)
    scores = cross_val_score(model, data[FEATURE_COLUMNS], data["label"], cv=LeaveOneGroupOut().split(data[FEATURE_COLUMNS], data["label"], groups))
    print(f"leave-one-session-out accuracy: {scores.mean():.3f} +/- {scores.std():.3f}")
    model.fit(data[FEATURE_COLUMNS], data["label"])
    labels = json.dumps(list(model.classes_))
    code = m2c.export_to_javascript(model, function_name="scoreArticulation")
    wrapper = f'''// Generated by train_articulation.py. Do not edit.
import type {{ ClassifierModel }} from "./types";

const labels = {labels};
{code}
export const articulationModel: ClassifierModel = {{
    trained: true,
    predict(features) {{
        const values = scoreArticulation(features);
        const probabilities = Object.fromEntries(labels.map((label, index) => [label, values[index] ?? 0]));
        const label = labels[values.indexOf(Math.max(...values))];
        return {{ label, probabilities }};
    }},
}};
'''
    args.out.write_text(wrapper, encoding="utf-8")


if __name__ == "__main__":
    main()