"""Train and export a single-stroke, motion-only articulation Random Forest."""
import argparse
import json
from pathlib import Path

import m2cgen as m2c
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import LeaveOneGroupOut, cross_val_score

from features import ARTICULATION_FEATURE_COLUMNS

FEATURE_COLUMNS = ARTICULATION_FEATURE_COLUMNS


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("csv", type=Path)
    parser.add_argument("--out", type=Path, default=Path("../lib/models/articulation.generated.ts"))
    args = parser.parse_args()
    data = pd.read_csv(args.csv)
    required = ["label", "performer_id", "session_id", "audio_valid", *FEATURE_COLUMNS]
    missing = [column for column in required if column not in data.columns]
    if missing:
        raise SystemExit(f"CSV is missing required columns: {', '.join(missing)}")
    data = data[data["audio_valid"].astype(str).str.lower().isin(["1", "true", "yes"])].copy()
    if data["label"].nunique() < 2:
        raise SystemExit("Need at least two articulation labels with valid audio to train.")

    model = RandomForestClassifier(
        n_estimators=80,
        max_depth=6,
        min_samples_leaf=2,
        random_state=42,
        class_weight="balanced",
    )
    groups = data["performer_id"].astype(str) + ":" + data["session_id"].astype(str)
    if groups.nunique() >= 2:
        scores = cross_val_score(model, data[FEATURE_COLUMNS], data["label"], cv=LeaveOneGroupOut().split(data[FEATURE_COLUMNS], data["label"], groups))
        print(f"leave-one-session-out accuracy: {scores.mean():.3f} +/- {scores.std():.3f}")
    else:
        print("leave-one-session-out accuracy: skipped (need at least two performer/session groups)")
    model.fit(data[FEATURE_COLUMNS], data["label"])
    labels = json.dumps(list(model.classes_))
    code = m2c.export_to_javascript(model, function_name="scoreArticulation")
    wrapper = f'''// Generated by train_articulation.py. Do not edit.
import type {{ ClassifierModel }} from "./types";

const labels = {labels};
{code}
export const articulationModel: ClassifierModel = {{
    trained: true,
    predict(features) {{
        const values = scoreArticulation(features);
        const probabilities = Object.fromEntries(labels.map((label, index) => [label, values[index] ?? 0]));
        const label = labels[values.indexOf(Math.max(...values))];
        return {{ label, probabilities }};
    }},
}};
'''
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(wrapper, encoding="utf-8")


if __name__ == "__main__":
    main()
